'use client'

import { Download } from 'lucide-react'
import type { SimulationBet, SimulationRace } from '@/lib/betting/historical-simulator'
import { tabPlaceCalibration, tabPlaceProspectiveReport } from '@/lib/betting/tab-place-research'

const money = (value: number) => new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD' }).format(value)
const percent = (value: number | null) => value === null ? '-' : `${value.toFixed(1)}%`
const score = (value: number | null | undefined) => value == null ? '-' : value.toFixed(4)

export function TabPlaceResearch({ races, onExport }: { races: SimulationRace[]; onExport: (bets: SimulationBet[]) => void }) {
  const report = tabPlaceProspectiveReport(races)
  const calibration = tabPlaceCalibration(races)
  const bets = report.cohorts.flatMap(cohort => cohort.bets)
  return <section aria-label="Prospective TAB PLACE research" className="space-y-4 border-y border-slate-200 py-5">
    <div className="flex items-center justify-between gap-3"><h3 className="font-semibold">Prospective TAB PLACE</h3><button type="button" aria-label="Export prospective TAB bets" title="Export prospective TAB bets" disabled={!bets.length} onClick={() => onExport(bets)} className="flex h-9 w-9 shrink-0 items-center justify-center rounded border border-slate-300 bg-white disabled:opacity-40"><Download size={16} /></button></div>
    <p className="text-xs text-slate-600">{report.rules.version} · {report.rules.model} · Raw-probability baseline · $1 flat / $500 per cohort · Edge at least 5 points · Estimated return at least 5% · Odds at most $15 · One selection per race.</p>
    <p role="status" className="border-l-4 border-amber-500 bg-amber-50 p-3 text-xs text-amber-950">{report.observedRaces} frozen seven/eight-runner observations; {report.eligibleRaces} eligible; {report.unknownTermsRaces} missing verified paid-place terms; {report.otherExcludedRaces} other evidence exclusions. {!report.eligibleRaces && 'No eligible trial results in this window. Verified pre-race TAB paid-place terms are required; the feed\'s race-level count does not identify TAB as its source.'}</p>
    <p className="text-xs text-slate-600">Completed races in the published window only, not lifetime totals. Older observations without the frozen trial rules are excluded. Seven runners require two verified places; eight require three. Unchanged fields, complete fresh TAB WIN ranks and PLACE prices are mandatory. Joint favourites remain favourites. No live bets or automatic model promotion.</p>
    <div className="overflow-x-auto" tabIndex={0} aria-label="TAB cohort comparison"><table className="w-full min-w-[1000px] text-left text-xs"><thead className="border-b text-slate-500"><tr>{['Starters', 'Cohort', 'Bets / races', 'Stake', 'Net profit', 'ROI', 'Hit rate', 'Expected hit rate', 'Drawdown', 'Review'].map(label => <th key={label} className="px-3 py-2">{label}</th>)}</tr></thead><tbody>{report.cohorts.map(cohort => <tr key={`${cohort.fieldSize}:${cohort.cohort}`} className="border-b border-slate-200 tabular-nums">
      <td className="px-3 py-3">{cohort.fieldSize}</td><th className="px-3 font-medium">{cohort.cohort}</th><td className="px-3">{cohort.summary?.bets ?? 0} / {cohort.summary?.races ?? 0}</td><td className="px-3">{money(cohort.summary?.staked ?? 0)}</td><td className="px-3">{money(cohort.summary?.profit ?? 0)}</td><td className="px-3">{percent(cohort.summary?.roi ?? null)}</td><td className="px-3">{percent(cohort.risk.hitRate === null ? null : cohort.risk.hitRate * 100)}</td><td className="px-3">{percent(cohort.risk.expectedHitRate === null ? null : cohort.risk.expectedHitRate * 100)}</td><td className="px-3">{money(cohort.risk.drawdown)} / {percent(cohort.summary?.maxDrawdown ?? null)}</td><td className="px-3">{cohort.risk.reviewReady ? 'Review only' : 'Insufficient sample'}</td>
    </tr>)}</tbody></table></div>
    <details><summary className="cursor-pointer text-sm font-medium">Losing periods and calibration</summary><div className="mt-3 overflow-x-auto" tabIndex={0} aria-label="TAB cohort risk"><table className="w-full min-w-[950px] text-left text-xs"><thead className="border-b text-slate-500"><tr>{['Starters / cohort', 'Betting days', 'Losing days', 'Worst day', 'Longest losing streak', 'Brier', 'Log loss', '95% hit-rate interval'].map(label => <th key={label} className="px-3 py-2">{label}</th>)}</tr></thead><tbody>{report.cohorts.map(cohort => <tr key={`${cohort.fieldSize}:${cohort.cohort}`} className="border-b border-slate-200 tabular-nums"><th className="px-3 py-3 font-medium">{cohort.fieldSize} / {cohort.cohort}</th><td className="px-3">{cohort.risk.days}</td><td className="px-3">{cohort.risk.losingDays}</td><td className="px-3">{cohort.risk.worstDay === null ? '-' : money(cohort.risk.worstDay)}</td><td className="px-3">{cohort.risk.longestLosingStreak}</td><td className="px-3">{score(cohort.risk.brier)}</td><td className="px-3">{score(cohort.risk.logLoss)}</td><td className="px-3">{cohort.risk.hitRateInterval?.map(value => percent(value * 100)).join(' to ') ?? '-'}</td></tr>)}</tbody></table></div>
      <p className="mt-3 text-xs text-slate-600">Review requires 300 distinct selected races across 30 betting days per cohort. Wilson hit-rate intervals are descriptive and do not account for within-day dependence. Repeatedly inspecting results does not establish significance or a profitable edge.</p>
    </details>
    <div className="space-y-2 border-t border-slate-200 pt-3"><h4 className="text-sm font-medium">TAB-specific calibration candidates</h4>{calibration.map(group => <div key={group.fieldSize} className="text-xs text-slate-600"><p>{group.fieldSize} runners / {group.fieldSize === 7 ? 'top-two Harville estimate' : 'top-three forecast'}: {group.races} verified races, {group.days} days. {group.status}.</p>{group.study && <p className="mt-1">Whole-day 60/20/20 split; strength fitted on {group.study.trainingRaces} training races: {score(group.study.strength)}. Validation Brier {score(group.study.validation.raw.brier)} to {score(group.study.validation.corrected.brier)}; test Brier {score(group.study.test?.raw.brier)} to {score(group.study.test?.corrected.brier)}. {group.study.eligibleForProspectiveReview ? 'Eligible for a separately frozen prospective review, not deployment.' : 'Not eligible for promotion.'}</p>}</div>)}</div>
  </section>
}